version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
     - "2181:2181"

  kafka-source:
    image: wurstmeister/kafka:2.12-2.8.0
    expose:
     - "9092"
    ports:
     - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-source:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "topic1:1:1,topic2:1:1"

  kafka-target:
    image: wurstmeister/kafka:2.12-2.8.0
    expose:
     - "9092"
    ports:
     - "9093:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-target:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "topic1:1:1,topic2:1:1"

  mirror-maker:
    image: confluentinc/cp-kafka:6.2.0
    command: ["bash", "-c", "bin/connect-mirror-maker /etc/kafka/connect-mirror-maker.properties"]
    volumes:
     - ./mirror-maker.properties:/etc/kafka/connect-mirror-maker.properties
    depends_on:
     - kafka-source
     - kafka-target
