version: '2'

services:
  zookeeper-source:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka-source:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-source:2181
    networks:
      - kafka-net

  zookeeper-target:
    image: bitnami/zookeeper:latest
    ports:
      - "2182:2181"
    networks:
      - kafka-net

  kafka-target:
    image: bitnami/kafka:latest
    ports:
      - "9093:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-target:2181
    networks:
      - kafka-net

  mirror-maker:
    image: bitnami/kafka:latest
    entrypoint: ["sh", "-c", "/opt/bitnami/kafka/bin/connect-mirror-maker.sh /opt/bitnami/kafka/config/mirror-maker.properties"]
    volumes:
      - ./mirror-maker.properties:/opt/bitnami/kafka/config/mirror-maker.properties
    depends_on:
      - kafka-source
      - kafka-target
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
